//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Table
    {
        public long Id { get; set; }
        public string question { get; set; }
        public string imageb64 { get; set; }
    }
}
